spring:
  profiles:
    #启动模式
    active: dev


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.entity

#    spring.profiles.active
##注册中心配置
#eureka:
#  instance:
#    #实例名称显示IP
#    preferIpAddress: true
#
#info:
#  app:
#    name: ${spring.application.name}