#服务配置
server:
  #启动端口
  port: 8100
  #内置TOMCAT配置
  tomcat:
    #uri编码
    uri-encoding: UTF-8
#数据库启动方式
#data:
#  #是否开启初始化
#  init: false
#  #脚本升级版本号
#  upgradeVersion: 0
#Spring配置
#spring:
#  security:
#    user:
#      name: admin
#      password: 123456
#  cloud:
#    config:
#      enabled: false
#      label: master
#      profile: dev
#      uri: http://127.0.0.1:8888/config/
#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#  servlet:
#    #文件上传配置
#    multipart:
#      #是否支持批量上传(默认值 true)
#      enabled: true
#      #上传文件的临时目录(一般情况下不用特意修改)
#      location:
#      #上传文件最大为 1M(默认值 1M 根据自身业务自行控制即可)
#      max-file-size: 32Mb
#      #上传请求最大为 10M(默认值10M 根据自身业务自行控制即可)
#      max-request-size: 128Mb
#      #文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中,(默认值0 一般情况下不用特意修改)
#      file-size-threshold: 0
#      #判断是否要延迟解析文件（相当于懒加载，一般情况下不用特意修改）
#      resolve-lazily: false
  #JACKSON配置
#  jackson:
#    #日期格式化
#    date-format: yyyy-MM-dd HH:mm:ss
#    #时区设置
#    time-zone: GMT+8
#    serialization:
#      #格式化输出
#      indent-output: true
#      #忽略无法转换的对象
#      fail-on-empty-beans: false
#      #设置空如何序列化
#    defaultPropertyInclusion: NON_NULL
#    deserialization:
#      #允许对象忽略json中不存在的属性
#      fail-on-unknown-properties: false
#    parser:
#      #允许出现特殊字符和转义符
#      allow-unquoted-control-chars: true
#      #允许出现单引号
#      allow-single-quotes: true
  #数据库配置

spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      #链接地址
      url: jdbc:mysql://localhost:3306/db_jwzt?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      #用户名
      username: root
      #密码
      password: root
      #数据库连接池类型
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j2
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #110数据库配置
#    db110:
#      #驱动名称
#      driverClassName: com.mysql.jdbc.Driver
#      #链接地址
#      url: jdbc:mysql://192.168.1.248:3306/db_jwzt1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#      #用户名
#      username: root
#      #密码
#      password: root
#      #数据库连接池类型
#      type: com.alibaba.druid.pool.DruidDataSource
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall,log4j2
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    #165数据库配置
#    db165:
#      #驱动名称
#      driverClassName: com.mysql.jdbc.Driver
#      #链接地址
#      url: jdbc:mysql://192.168.1.248:3306/sql_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#      #用户名
#      username: root
#      #密码
#      password: root
#      #数据库连接池类型
#      type: com.alibaba.druid.pool.DruidDataSource
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall,log4j2
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #Redis配置
  redis:
    #Redis数据库索引(默认为0)
    database: 3
    #Redis服务器地址
    host: 192.168.1.248
    #是否启用SSL支持。
    ssl: false
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码(默认为空)
    password:
    #连接超时时间(毫秒)
    timeout: 2000ms
    #Redis连接池配置
    lettuce:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 100
        #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1ms
        #连接池中的最大空闲连接
        max-idle: 100
        #连接池中的最小空闲连接
        min-idle: 0

#文件上传配置
upload:
  #上传文件的磁盘存储路径
  disk: /Users/jiang/testfile/
#dtsql
#dtsql:
#  host: 192.168.1.253
#  port: 8001

logging:
  level:
    com.dtdream.mapper: debug
    com.dtdream.db110.mapper: debug
    com.dtdream.db165.mapper: debug

##分页工具配置
#pagehelper:
#  #对应使用数据库
#  helperDialect: mysql
#  #分页合理化参数，默认false。当为true时,pageNum<=0 时会查询第一页,pageNum>pages(超过总数时)会查询最后一页。为false时,直接根据参数进行查询。
#  reasonable: false
#  #支持通过 Mapper 接口参数来传递分页参数
#  supportMethodsArguments: true
#  #从对象中根据属性名取值
#  params: count=countSql

#eureka:
#  instance:
#    hostname: 192.168.1.248
#    #强制指定IP地址，默认会获取本机的IP地址
#    #ip-address: 192.168.1.248
#  client:
##    register-with-eureka: false
##    fetch-registry: false
#    eureka-server-port: 8000
#    serviceUrl:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
#
#security:
#  oauth2:
#    client:
#      client-id: user-client
#      client-secret: user-client-secret
#      scope: user
#      access-token-uri: http://192.168.1.248:8500/oauth/token
#      user-authorization-uri: http://192.168.1.248:8500/oauth/authorize
#    resource:
#      token-info-uri: http://192.168.1.248:8500/oauth/check_token
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: info,health,refresh
#
#patterns:
#   /**
##  /,
##  /actuator/**,
##  /fileResource/**,
##  /swagger-resources/**,
##  /webjars/**,
##  /v2/**,
##  /swagger-ui.html/**
#
#
#ribbon:
#   ReadTimeout: 60000
#   ConnectTimeout: 60000
#
#feign:
#  client:
#    config:
#      default:
#        readTimeout: 60000
#        connectTimeout: 60000
